// <auto-generated />
namespace Event_manager_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SumOpTweeMigratie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SumOpTweeMigratie));
        
        string IMigrationMetadata.Id
        {
            get { return "201912292020511_SumOpTweeMigratie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
